name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
    
    - name: 安装Python依赖
      run: |
        python -m pip install --upgrade pip
        pip install kivy buildozer cython
    
    - name: 缓存Buildozer构建文件
      uses: actions/cache@v3
      with:
        path: |
          .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
    
    - name: 构建Android APK
      run: |
        buildozer android debug
    
    - name: 上传APK文件
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
        compression-level: 6
